version: '3'
services:
  db:
    image: postgres:13
    container_name: FYP_Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - final_year_project

  react:
    image: node:latest
    container_name: react_app
    working_dir: /app
    volumes:
      - ./FinalYearProject:/client # Mount the entire project directory
    ports:
      - "3000:3000"
    command: [ "sh", "-c", "npm install && npm start --prefix client" ]
    networks:
      - final_year_project

networks:
  final_year_project:
    external: true
